### ISSUE TITLE
Find the path from start to goal.

### ISSUE THREAD

**Issue by seongyooncho** [potluck-robotics/sdl-astar#1]
Starting from the goal node, follow the parent node until finding the start node. The path should be the most optimal path.

**Comment by donghee** [comment]
Check reconstruct path from [Pseudocode](https://en.wikipedia.org/wiki/A*_search_algorithm)

**Comment by donghee** [comment]
Inspect the memory state of the node parent element from [AStar::ReconstructPath()](https://github.com/potluck-robotics/sdl-astar/blob/9eeed646b9c56638a496c578f31862be701170db/src/a_star.cpp#L134) function 
 
<img width="948" alt="image" src="https://github.com/potluck-robotics/sdl-astar/assets/91220/00ed37d2-a8c2-424f-8f3c-f89781a6e288">

**Comment by seongyooncho** [comment]
[<img width="347" alt="image" src="https://github.com/potluck-robotics/sdl-astar/assets/679696/61d88e21-5719-46dd-83d7-b86d6457e389">
](https://youtu.be/Ce3F03SM1ac)
