### ISSUE TITLE
Enhance a* search performance

### ISSUE THREAD

**Issue by donghee** [potluck-robotics/sdl-astar#11]
It become very slow in certain conditions.

**Comment by seongyooncho** [comment]
https://github.com/potluck-robotics/sdl-astar/assets/679696/08fa270d-b96a-4acc-85a0-81bc06e896fa

**Comment by seongyooncho** [comment]
We found the open list and the closed list grows very big. So we have replaced the existing node when pushing back to the open list.
| Redundant nodes in the list | After checking existing node |
| --- | --- |
| ![image](https://github.com/potluck-robotics/sdl-astar/assets/679696/1e79d83b-7d66-42d4-8539-6419eee5d911) | ![image](https://github.com/potluck-robotics/sdl-astar/assets/679696/6858c8d5-3ead-42e1-97f9-f8244cc1ba11) |
